In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import os

In [2]:
folder = os.listdir()
folder

['.ipynb_checkpoints',
 'biofuel-production.csv',
 'code.ipynb',
 'cumulative-installed-wind-energy-capacity-gigawatts.csv',
 'hydro-share-energy.csv',
 'hydropower-consumption.csv',
 'installed-geothermal-capacity.csv',
 'installed-solar-PV-capacity.csv',
 'modern-renewable-energy-consumption.csv',
 'modern-renewable-prod.csv',
 'renewable-share-energy.csv',
 'share-electricity-hydro.csv',
 'share-electricity-renewables.csv',
 'share-electricity-solar.csv',
 'share-electricity-wind.csv',
 'solar-energy-consumption.csv',
 'solar-share-energy.csv',
 'wind-generation.csv',
 'wind-share-energy.csv']

In [6]:
# lets add file paths
dataframe = pd.DataFrame()
for path in folder[1:]:
    table = pd.read_csv(path) # read the csv of the individual files
    data = pd.concat([dataframe,table],ignore_index= False)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

In [4]:
folder[1:]

['biofuel-production.csv',
 'code.ipynb',
 'cumulative-installed-wind-energy-capacity-gigawatts.csv',
 'hydro-share-energy.csv',
 'hydropower-consumption.csv',
 'installed-geothermal-capacity.csv',
 'installed-solar-PV-capacity.csv',
 'modern-renewable-energy-consumption.csv',
 'modern-renewable-prod.csv',
 'renewable-share-energy.csv',
 'share-electricity-hydro.csv',
 'share-electricity-renewables.csv',
 'share-electricity-solar.csv',
 'share-electricity-wind.csv',
 'solar-energy-consumption.csv',
 'solar-share-energy.csv',
 'wind-generation.csv',
 'wind-share-energy.csv']

In [5]:
data.sample(10)

                   0    1     2      3   4   5   6   7   8   9
4046     Switzerland  CHE  1975      0 NaN NaN NaN NaN NaN NaN
2316          Kuwait  KWT  1983      0 NaN NaN NaN NaN NaN NaN
2177           Italy  ITA  1992      0 NaN NaN NaN NaN NaN NaN
4567   United States  USA  2012  1.472 NaN NaN NaN NaN NaN NaN
2925        Non-OECD  NaN  2016      1 NaN NaN NaN NaN NaN NaN
2403       Lithuania  LTU  1998      0 NaN NaN NaN NaN NaN NaN
2562          Mexico  MEX  1989      0 NaN NaN NaN NaN NaN NaN
1303         Estonia  EST  2014  2.043 NaN NaN NaN NaN NaN NaN
665              CIS  NaN  2003      0 NaN NaN NaN NaN NaN NaN
4468  United Kingdom  GBR  1969      0 NaN NaN NaN NaN NaN NaN